### ISSUE TITLE
If disks gets ejected games from emulators (retroarch) appear as not installed.

### ISSUE THREAD

**Issue by Hedronmx** [tkashkin/GameHub#124]
If I remove my disk (not mounted) and open gamehub, previously install games, specifically ones using retroarch, appear as uninstalled.
Then after I mount my disk again, they remain uninstalled.

![Image](https://i.imgur.com/S7zFqqm.jpg)

**Comment by tkashkin** [comment]
It may be already fixed in 9148625.

**Comment by tkashkin** [comment]
Test 1c78c4f.

**Comment by Hedronmx** [comment]
Is not fixed, they still appeared as not installed.
I remove all of them and added one game to see if its fixed.

**Comment by tkashkin** [comment]
It probably resets `install_dir` to `null` if it doesn't exist.

**Comment by Hedronmx** [comment]
It seems like it, the only ones that do reappear are steam games.

**Comment by Hedronmx** [comment]
It seems fixed!
